project_id = "wrmmvbqzpnphzhozgxeh"

[functions.generate-image]
verify_jwt = false

[functions.ai-filter]
verify_jwt = false

[functions.resolve-votes]
verify_jwt = false

[functions.remix-post]
verify_jwt = false

[functions.evolve-post]
verify_jwt = false